### ISSUE TITLE
BUG - Gist is not opened in browser after creating

### ISSUE THREAD

**Issue by piotrpalarz** [kenhowardpdx/vscode-gist#92]
**This is a**

- [x] bug report
- [ ] feature request

#### Description

Extension Version: 2.1.2
VS Code Version: 1.30.2
OS: macOS 10.14.2

After adding Gist via **GIST: Create New Gist** it's not opened in the browser like it did before. Insted a file is opened in the VS Code with a path like this: `/var/folders/1c/_lydnfvj6c3fsjc9mfx8fsjw0000gn/T/vscode_gist_c06b732bef6d5e4cd81b052c972f8313_73713fpsKhux7zdYv/cuepoints.js` The Gist is correctly added to the GitHub account though.

**Comment by kenhowardpdx** [comment]
This is new behavior and working as expected. Because I didn't have telemetry data previously I didn't have any idea which features people were using. I'm going to keep this bug ticket open to see if anyone else is unhappy with this behavior. The current user flow would be `create gist` > `open gist in browser`. That should satisfy your expected behavior until I get consensus on how people are using the extension.

**Comment by piotrpalarz** [comment]
Thank you for your reply.

This feature is important to me because we have set up guidlines for authors of our courses at eduweb.pl which include creating code snippets (Gists). Our current workflow was like this:

1. Create a Gist from VS Code
2. Copy its ID from the URL opened in the browser
3. Paste that ID in the author's panel to assign it to a lesson

And now we don't have that ID to be easily copied. Maybe you could add a setting to toggle that behaviour on/off (opening in the browser)?

**Comment by kenhowardpdx** [comment]
Is the gist Id the important part here? Or the gist actually opening in the browser?

**Comment by piotrpalarz** [comment]
The Gist ID is what we care about but since it was opening it in the browser we could copy it from the URL easily.

**Comment by kenhowardpdx** [comment]
Ok. I have some thoughts on this and it's super helpful to have @bertrandom's pull request to help inform my opinion.

What if, instead of opening a gist in a browser and automatically putting the gist URL in the users clipboard (per #93), I add buttons to the notification that will, when clicked, open the gist in a browser or copy the gist url to the clipboard?

This adds the desired behavior in a way that doesn't break the current flow but puts the power in the users hands as what to do when a gist is created. (I do not want to magically pollute the users clipboard, that's a sacred space)

**Comment by kenhowardpdx** [comment]
This is looking pretty good. I still have work to do before I can get a release out with this feature. I'll update this thread when I have a better idea when this will be out.

![vscode-confirm-create-dialog](https://user-images.githubusercontent.com/1892667/51436123-c8431b00-1c3b-11e9-91b3-ddefedb4b44a.gif)
