### ISSUE TITLE
BUG wrong type (public/private) of gists 

### ISSUE THREAD

**Issue by MecRND** [kenhowardpdx/vscode-gist#96]
- [ x] bug report
- [ ] feature request

#### Description

All gists marked has private are public and all gists marked has public are private.

F1 > GIST: Open Gist to see the list with wrong label

VS Code: Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-08T23:10:56.746Z
Electron: 2.0.16
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.19.16-1-MANJARO
Gists addons: 2.1.2 (2019-01-12)

**Comment by kenhowardpdx** [comment]
I have confirmed that when creating a new gist you can select "Y" for public and "N" for private. The bug is in the label, not the behavior. When viewing your gists in the select dropdown the Gists are incorrectly labeled. They are labeled "PUBLIC" when they are PRIVATE, and labeled "PRIVATE" when they are PUBLIC.
